#!/bin/bash
#	dmonitor	1.1	2017-12-20_20:40:40_CST uadmin
#	added date and version mark to file
#
#       set -x
#       set -v
#	set -e
#
#       monitor local host docker contaier resource usage statistics
#
docker stats $(docker ps|grep -v "NAMES"|awk '{ print $NF }'|tr "\n" " ")
